import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(req: Request) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return new Response("Unauthorized", { status: 401 });
    }

    const { projectId, githubToken, repoName, commitMessage } = await req.json();

    if (!projectId || !githubToken || !repoName) {
      return NextResponse.json({ error: "Missing required parameters" }, { status: 400 });
    }

    // Parse owner and repo e.g. "username/repo"
    const parts = repoName.split("/");
    if (parts.length !== 2) {
      return NextResponse.json({ error: "Invalid repository format. Must be 'owner/repo'" }, { status: 400 });
    }
    const [owner, repo] = parts;

    // 1. Fetch files from Supabase
    const { data: files, error: filesErr } = await supabase
      .from("project_files")
      .select("path, content")
      .eq("project_id", projectId);

    if (filesErr || !files || files.length === 0) {
      return NextResponse.json({ error: "No files found for this project" }, { status: 400 });
    }

    const headers = {
      Authorization: `token ${githubToken}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
      "User-Agent": "Opviber-App-Builder",
    };

    // 2. Check if repository exists. If not, create it.
    let repoExists = false;
    try {
      const checkRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers });
      if (checkRes.ok) {
        repoExists = true;
      } else if (checkRes.status === 404) {
        // Try creating repository
        const createRes = await fetch("https://api.github.com/user/repos", {
          method: "POST",
          headers,
          body: JSON.stringify({
            name: repo,
            description: "Generated by Opviber AI App Builder",
            private: false,
            auto_init: false,
          }),
        });

        if (!createRes.ok) {
          const errData = await createRes.json();
          throw new Error(errData.message || "Failed to create GitHub repository");
        }
        repoExists = true;
      } else {
        const errData = await checkRes.json();
        throw new Error(errData.message || "Failed to access GitHub repository");
      }
    } catch (err: any) {
      return NextResponse.json({ error: err.message || "GitHub access failed" }, { status: 520 });
    }

    // 3. Get latest commit/branch reference (e.g. main)
    let baseTreeSha: string | null = null;
    let parentCommitSha: string | null = null;
    let branchExists = false;
    let targetBranch = "main";

    const refRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${targetBranch}`, { headers });
    
    if (refRes.ok) {
      const refData = await refRes.json();
      parentCommitSha = refData.object.sha;
      branchExists = true;

      // Get the tree SHA of that commit
      const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits/${parentCommitSha}`, { headers });
      if (commitRes.ok) {
        const commitData = await commitRes.json();
        baseTreeSha = commitData.tree.sha;
      }
    } else {
      // Branch doesn't exist yet, we will create it as a new initial branch
      // But GitHub API requires a parent commit to create a branch reference via refs API
      // If the repo is empty, we must initialize it. The easiest way is to create a README.md file via Content API
      const readmePayload = {
        message: "Initial commit",
        content: Buffer.from("# " + repo + "\n\nGenerated by Opviber.").toString("base64"),
      };
      
      const initRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/README.md`, {
        method: "PUT",
        headers,
        body: JSON.stringify(readmePayload),
      });

      if (initRes.ok) {
        const initData = await initRes.json();
        parentCommitSha = initData.commit.sha;
        baseTreeSha = initData.commit.tree.sha;
        branchExists = true;
      } else {
        const errData = await initRes.json();
        return NextResponse.json({ error: errData.message || "Failed to initialize repository" }, { status: 500 });
      }
    }

    // 4. Create the Git tree with the files
    const treeNodes = files.map((file) => ({
      path: file.path,
      mode: "100644",
      type: "blob",
      content: file.content || " ",
    }));

    const createTreePayload = {
      base_tree: baseTreeSha || undefined,
      tree: treeNodes,
    };

    const treeRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees`, {
      method: "POST",
      headers,
      body: JSON.stringify(createTreePayload),
    });

    if (!treeRes.ok) {
      const errData = await treeRes.json();
      return NextResponse.json({ error: errData.message || "Failed to build Git tree on GitHub" }, { status: 500 });
    }

    const treeData = await treeRes.json();
    const newTreeSha = treeData.sha;

    // 5. Create the Git commit
    const createCommitPayload = {
      message: commitMessage || "Updates from Opviber Workspace",
      tree: newTreeSha,
      parents: parentCommitSha ? [parentCommitSha] : [],
    };

    const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits`, {
      method: "POST",
      headers,
      body: JSON.stringify(createCommitPayload),
    });

    if (!commitRes.ok) {
      const errData = await commitRes.json();
      return NextResponse.json({ error: errData.message || "Failed to create commit on GitHub" }, { status: 550 });
    }

    const commitData = await commitRes.json();
    const newCommitSha = commitData.sha;

    // 6. Update the branch ref to point to the new commit
    const updateRefUrl = `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${targetBranch}`;
    const updateRefPayload = {
      sha: newCommitSha,
      force: true,
    };

    const updateRes = await fetch(updateRefUrl, {
      method: "PATCH",
      headers,
      body: JSON.stringify(updateRefPayload),
    });

    if (!updateRes.ok) {
      const errData = await updateRes.json();
      return NextResponse.json({ error: errData.message || "Failed to update repository reference" }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      repoUrl: `https://github.com/${owner}/${repo}`,
      branch: targetBranch,
    });

  } catch (error: any) {
    console.error("GitHub push error:", error);
    return NextResponse.json({ error: error.message || "Internal server error" }, { status: 500 });
  }
}
