"use client";

import React, { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { useProjectStore } from "@/stores/project";
import { useUserStore } from "@/stores/user";
import FileExplorer from "@/components/workspace/FileExplorer";
import CodeEditor from "@/components/workspace/CodeEditor";
import ChatPanel from "@/components/workspace/ChatPanel";
import PreviewPanel from "@/components/workspace/PreviewPanel";
import DatabaseViewer from "@/components/workspace/DatabaseViewer";
import AdvisorPanel from "@/components/workspace/AdvisorPanel";
import { Sparkles, LogOut, Loader2, ArrowLeft, Folder, Database, HelpCircle, Download, GitBranch } from "lucide-react";
import Link from "next/link";
import JSZip from "jszip";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

export default function WorkspacePage() {
  const params = useParams();
  const router = useRouter();
  const projectId = params.projectId as string;
  
  const { loadProject, projectName, files, isLoading } = useProjectStore();
  const { loadUser, profile } = useUserStore();
  const [activeSidebarTab, setActiveSidebarTab] = useState<"files" | "database" | "advisor">("files");

  // GitHub integration state
  const [isGitHubOpen, setIsGitHubOpen] = useState(false);
  const [githubToken, setGithubToken] = useState("");
  const [repoName, setRepoName] = useState("");
  const [commitMessage, setCommitMessage] = useState("Updates from Opviber Workspace");
  const [isPushing, setIsPushing] = useState(false);

  useEffect(() => {
    if (projectId) {
      loadProject(projectId);
      loadUser();
    }
  }, [projectId]);

  const handleExportZip = async () => {
    const zip = new JSZip();
    
    // Add all project files
    Object.keys(files).forEach((path) => {
      zip.file(path, files[path].content);
    });

    // Add default files if missing
    if (!files["package.json"]) {
      const pkgJson = {
        name: projectName.toLowerCase().replace(/[^a-z0-9]/g, "-"),
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start"
        },
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          next: "^14.1.0",
          "lucide-react": "^0.300.0",
          "tailwind-merge": "^2.2.0"
        }
      };
      zip.file("package.json", JSON.stringify(pkgJson, null, 2));
    }

    if (!files["README.md"]) {
      const readme = `# ${projectName}

Generated by [Opviber](https://opviber.com) — The AI App Builder.

## Getting Started

Install dependencies:
\`\`\`bash
npm install
\`\`\`

Run the development server:
\`\`\`bash
npm run dev
\`\`\`
`;
      zip.file("README.md", readme);
    }

    try {
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${projectName.toLowerCase().replace(/[^a-z0-9]/g, "-")}-code.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success("Project files exported as ZIP successfully!");
    } catch (err) {
      console.error("ZIP creation failed:", err);
      toast.error("Failed to generate project ZIP export.");
    }
  };

  const handleGitHubPush = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!githubToken.trim() || !repoName.trim()) {
      toast.error("Please enter both your GitHub Token and Repo Name.");
      return;
    }

    setIsPushing(true);
    try {
      const res = await fetch("/api/projects/github/push", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          projectId,
          githubToken: githubToken.trim(),
          repoName: repoName.trim(),
          commitMessage: commitMessage.trim(),
        }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || "GitHub commit failed");
      }

      toast.success("Successfully pushed to GitHub repo!");
      setIsGitHubOpen(false);
      if (data.repoUrl) {
        window.open(data.repoUrl, "_blank");
      }
    } catch (err: any) {
      console.error(err);
      toast.error(err.message || "Failed to push project to GitHub.");
    } finally {
      setIsPushing(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-zinc-950 text-white gap-3">
        <Loader2 size={32} className="animate-spin text-violet-500" />
        <span className="text-sm text-zinc-400">Loading your workspace modules...</span>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-screen w-screen bg-zinc-950 text-zinc-100 overflow-hidden font-sans">
      {/* Workspace Header */}
      <header className="flex items-center justify-between px-4 py-2 border-b border-zinc-900 bg-zinc-950 z-10 shrink-0">
        <div className="flex items-center gap-3">
          <Link href="/projects" className="p-1.5 hover:bg-zinc-900 rounded text-zinc-400 hover:text-white transition">
            <ArrowLeft size={16} />
          </Link>
          <div className="flex items-center gap-2">
            <div className="h-6 w-6 bg-violet-600 rounded flex items-center justify-center font-bold text-xs">O</div>
            <span className="font-bold text-sm">{projectName || "Untitled Project"}</span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Export ZIP */}
          <Button
            variant="ghost"
            size="sm"
            onClick={handleExportZip}
            className="h-8 gap-1.5 text-xs text-zinc-400 hover:text-white transition hover:bg-zinc-900 cursor-pointer"
          >
            <Download size={14} />
            Export ZIP
          </Button>

          {/* GitHub Dialog */}
          <Dialog open={isGitHubOpen} onOpenChange={setIsGitHubOpen}>
            <DialogTrigger render={
              <Button
                variant="ghost"
                size="sm"
                className="h-8 gap-1.5 text-xs text-zinc-400 hover:text-white transition hover:bg-zinc-900 cursor-pointer"
              >
                <GitBranch size={14} />
                Push to GitHub
              </Button>
            } />
            <DialogContent className="bg-zinc-900 border-zinc-850 text-white">
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  <GitBranch size={18} className="text-violet-400" />
                  Push to GitHub Repository
                </DialogTitle>
              </DialogHeader>
              <form onSubmit={handleGitHubPush} className="space-y-4 pt-2">
                <div className="space-y-2">
                  <label className="text-xs text-zinc-400">GitHub Personal Access Token (PAT)</label>
                  <Input
                    type="password"
                    placeholder="ghp_..."
                    value={githubToken}
                    onChange={(e) => setGithubToken(e.target.value)}
                    className="bg-zinc-950 border-zinc-800 text-white placeholder-zinc-650 text-xs focus-visible:ring-violet-600"
                    required
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-xs text-zinc-400">Repository Name</label>
                  <Input
                    placeholder="e.g. username/repo-name"
                    value={repoName}
                    onChange={(e) => setRepoName(e.target.value)}
                    className="bg-zinc-950 border-zinc-800 text-white placeholder-zinc-650 text-xs focus-visible:ring-violet-600"
                    required
                  />
                  <p className="text-[10px] text-zinc-500">
                    If the repository does not exist, Opviber will create a public repository automatically.
                  </p>
                </div>
                <div className="space-y-2">
                  <label className="text-xs text-zinc-400">Commit Message</label>
                  <Input
                    placeholder="Updates from Opviber Workspace"
                    value={commitMessage}
                    onChange={(e) => setCommitMessage(e.target.value)}
                    className="bg-zinc-950 border-zinc-800 text-white placeholder-zinc-650 text-xs focus-visible:ring-violet-600"
                  />
                </div>
                <div className="flex justify-end gap-2 pt-2">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setIsGitHubOpen(false)}
                    className="bg-transparent border-zinc-800 text-zinc-400 hover:bg-zinc-800 hover:text-white"
                  >
                    Cancel
                  </Button>
                  <Button
                    type="submit"
                    disabled={isPushing}
                    className="bg-violet-600 hover:bg-violet-750 text-white gap-1.5"
                  >
                    {isPushing ? (
                      <>
                        <Loader2 size={12} className="animate-spin" />
                        Pushing...
                      </>
                    ) : (
                      <>
                        <GitBranch size={12} />
                        Push Code
                      </>
                    )}
                  </Button>
                </div>
              </form>
            </DialogContent>
          </Dialog>

          <div className="w-[1px] h-4 bg-zinc-800 mx-1" />

          <Link href="/projects">
            <button className="flex items-center gap-1.5 text-xs text-zinc-400 hover:text-white transition h-8 px-2 rounded hover:bg-zinc-900 cursor-pointer">
              <LogOut size={14} />
              Exit
            </button>
          </Link>
        </div>
      </header>

      {/* Main Panel Split */}
      <div className="flex flex-1 overflow-hidden min-h-0">
        {/* Activity Bar (VS Code Style) */}
        <div className="w-12 shrink-0 bg-zinc-950 border-r border-zinc-900 flex flex-col items-center py-4 gap-4">
          <button
            onClick={() => setActiveSidebarTab("files")}
            className={`p-2 rounded-lg transition-all cursor-pointer ${
              activeSidebarTab === "files" ? "text-violet-400 bg-zinc-900" : "text-zinc-500 hover:text-zinc-300"
            }`}
            title="File Explorer"
          >
            <Folder size={18} />
          </button>

          <button
            onClick={() => setActiveSidebarTab("database")}
            className={`p-2 rounded-lg transition-all cursor-pointer ${
              activeSidebarTab === "database" ? "text-violet-400 bg-zinc-900" : "text-zinc-550 hover:text-zinc-300"
            }`}
            title="Database & Schema Viewer"
          >
            <Database size={18} />
          </button>

          <button
            onClick={() => setActiveSidebarTab("advisor")}
            className={`p-2 rounded-lg transition-all cursor-pointer ${
              activeSidebarTab === "advisor" ? "text-violet-400 bg-zinc-900" : "text-zinc-550 hover:text-zinc-300"
            }`}
            title="Product Advisor"
          >
            <HelpCircle size={18} />
          </button>
        </div>

        {/* Sidebar Panel Content */}
        <div className="w-64 shrink-0 h-full flex flex-col">
          {activeSidebarTab === "files" && <FileExplorer />}
          {activeSidebarTab === "database" && <DatabaseViewer />}
          {activeSidebarTab === "advisor" && <AdvisorPanel />}
        </div>

        {/* Center - Monaco Code Editor */}
        <div className="flex-1 h-full min-w-0 flex flex-col">
          <CodeEditor />
        </div>

        {/* Right Side - Split Chat & Preview */}
        <div className="w-[500px] shrink-0 h-full flex flex-col border-l border-zinc-800/80 min-h-0">
          {/* Top - Live Preview */}
          <PreviewPanel />

          {/* Bottom - AI Chat Panel */}
          <ChatPanel />
        </div>
      </div>
    </div>
  );
}
